services:
  api:
    build: .
    container_name: fastapi_ecommerce_api_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      DEBUG: "false"
      LOG_LEVEL: "INFO"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/fastapi_ecommerce"
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 2 --timeout 120

  db:
    image: postgres:16
    container_name: fastapi_ecommerce_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_prod_data:
