"""create vouchers and add discount fields to orders

Revision ID: b00222faf979
Revises: ee4fe66a37c9
Create Date: 2026-06-13 16:52:18.929341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b00222faf979'
down_revision: Union[str, Sequence[str], None] = 'ee4fe66a37c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=False),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('voucher_id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=False)
    op.create_index(op.f('ix_vouchers_discount_type'), 'vouchers', ['discount_type'], unique=False)
    op.create_index(op.f('ix_vouchers_is_active'), 'vouchers', ['is_active'], unique=False)
    op.add_column('orders',sa.Column('sub_total', sa.Float(), nullable=False, server_default='0'),)
    op.add_column('orders',sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'),)
    op.add_column('orders', sa.Column('voucher_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_orders_voucher_code'), 'orders', ['voucher_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_voucher_code'), table_name='orders')
    op.drop_column('orders', 'voucher_code')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'sub_total')
    op.drop_index(op.f('ix_vouchers_is_active'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_discount_type'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
