"""create payments table

Revision ID: ee4fe66a37c9
Revises: 0f0672a719d0
Create Date: 2026-06-13 16:36:48.434804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ee4fe66a37c9'
down_revision: Union[str, Sequence[str], None] = '0f0672a719d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_no'), 'payments', ['transaction_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_no'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
